services:
  postgres:
    image: postgres:16-alpine
    container_name: sql-practice-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sqlpracticedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - sql-practice-network

  testrunner:
    build:
      context: ./TestRunner
      dockerfile: Dockerfile
    container_name: sql-practice-testrunner
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./users:/app/users:ro
      - ./solution-script:/app/solution-script:ro
      - ./results:/app/results
    networks:
      - sql-practice-network
    profiles:
      - test

volumes:
  postgres_data:

networks:
  sql-practice-network:
    driver: bridge
